[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.27"


remappings = [
    '@openzeppelin=lib/openzeppelin-contracts'
]

chain_id = 2442  # Polygon zkEVM Testnet - https://chainid.network/
[rpc_endpoints]
mumbai = "https://rpc.cardona.zkevm-rpc.com"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


